name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Endre hvis din hovedgren har et annet navn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js (required for npm scripts)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Eller en annen versjon du bruker

      - name: Inject API key into JavaScript
        run: |
          echo "const API_KEY = '${{ secrets.FIREBASE_API_KEY }}';" > ./config.js
