name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow når det er en push til "main"-grenen

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Gir skrivertilgang til innholdet i repoet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create public directory if it does not exist
        run: mkdir -p public

      - name: Inject Firebase API Key into config.js
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: 'qme1-423d8.firebaseapp.com',
            projectId: 'qme1-423d8',
            storageBucket: 'qme1-423d8.appspot.com',
            messagingSenderId: '425603580627',
            appId: '1:425603580627:web:c671dd03b1c40136370a26',
            measurementId: 'G-CSQGSQWCXT'
          };" > public/config.js

      - name: Commit and push config.js to main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/config.js
          git commit -m "Add config.js"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
