name: Secure Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Inject API Key into Config File
      run: |
        echo "const firebaseConfig = {" > public/firebaseConfig.js
        echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> public/firebaseConfig.js
        echo "  authDomain: 'qme1-423d8.firebaseapp.com'," >> public/firebaseConfig.js
        echo "  projectId: 'qme1-423d8'," >> public/firebaseConfig.js
        echo "  storageBucket: 'qme1-423d8.appspot.com'," >> public/firebaseConfig.js
        echo "  messagingSenderId: '425603580627'," >> public/firebaseConfig.js
        echo "  appId: '1:425603580627:web:c671dd03b1c40136370a26'," >> public/firebaseConfig.js
        echo "  measurementId: 'G-CSQGSQWCXT'" >> public/firebaseConfig.js
        echo "};" >> public/firebaseConfig.js
