name: Firebase

on:
  push:
    branches:
      - main  # Kjører når det er en push til "main"-grenen

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create public directory if it does not exist
        run: mkdir -p public

      - name: Inject Firebase API Key
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: 'qme1-423d8.firebaseapp.com',
            projectId: 'qme1-423d8',
            storageBucket: 'qme1-423d8.appspot.com',
            messagingSenderId: '425603580627',
            appId: '1:425603580627:web:c671dd03b1c40136370a26',
            measurementId: 'G-CSQGSQWCXT'
          };" > public/config.js

      - name: Verify config.js content
        run: cat public/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
