name: Secure Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create public directory if it doesn't exist
      run: mkdir -p public
    
    - name: Build project
      run: |
        echo "window.firebaseConfig = {
          apiKey: '${{ secrets.FIREBASE_API_KEY }}',
          authDomain: 'qme1-423d8.firebaseapp.com',
          projectId: 'qme1-423d8',
          storageBucket: 'qme1-423d8.appspot.com',
          messagingSenderId: '425603580627',
          appId: '1:425603580627:web:c671dd03b1c40136370a26',
          measurementId: 'G-CSQGSQWCXT'
        };" > public/firebaseConfig.js

      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
